export const type = {
    // Sync
    FILL_COMMENTS:        'FILL_COMMENTS',
    CREATE_COMMENT:       'CREATE_COMMENT',
    // Async
    FETCH_COMMENTS_ASYNC: 'FETCH_COMMENTS_ASYNC',
    CREATE_COMMENT_ASYNC: 'CREATE_COMMENT_ASYNC',
};
